### ISSUE TITLE
Xamarin NuGet 0.6.2 problem

### ISSUE THREAD

**Issue by mghiasi75** [Microsoft/project-rome#32]
After updating the Xamarin NuGet package to 0.6.2 (from 0.4.0), I'm getting this warning: 

> There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Microsoft.ConnectedDevices.Xamarin.Droid, Version=0.6.2.0, Culture=neutral, processorArchitecture=x86", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

Shouldn't Xamarin package be available on ARM too?

**Comment by cmknox** [comment]
@mghiasi75 the Xamarin library released is configured for x86 only, but the AAR inside it is built for ARM only. When building an Android app targeting ARM, Visual Studio will complain because it thinks the library is only for x86, but it will work fine deploying to an ARM device.  However, this shouldn't impact your app consuming the library.

**Comment by mghiasi75** [comment]
Thanks.
